apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app-deployment
  labels: { app: test-app }
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: { app: test-app }
  template:
    metadata:
      labels: { app: test-app }
    spec:
      containers:
        - name: test-app-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000